name: CI

on:
  pull_request:
    branches:
      - "*"  # Runs on all branches for pull requests

jobs:
  rust-ci:
    name: Rust CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run cargo fmt --check
      run: cargo fmt --check

    - name: Run cargo clippy --check
      run: cargo clippy -- -D warnings

    - name: Run cargo test
      run: cargo test --all

    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Generate code coverage report
      run: cargo tarpaulin --out html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: tarpaulin-coverage-report
        path: tarpaulin-report.html
