name: Rust CI

on:
  pull_request:
    branches:
      - "*"  # Runs on all branches for pull requests

jobs:
  rust-ci:
    name: Rust CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run cargo fmt
      run: |
        cargo fmt -- --check 2>&1 | tee rust-fmt.log

    - name: Run cargo clippy
      run: |
        cargo clippy -- -D warnings 2>&1 | tee clippy.log

    - name: Run cargo test
      run: |
        cargo test --all 2>&1 | tee cargo-test.log

    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Generate code coverage report
      run: cargo tarpaulin --out html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: ci-logs
        path: |
          rust-fmt.log
          clippy.log
          cargo-test.log
          tarpaulin-report.html
